version: '3'
services:
  app:
    build: .
    ports:
     - '3000:3000'
    depends_on:
      - redis
    volumes:
      - './src:/usr/src/app/src'
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'